#!/usr/bin/env bash
set -e

# install gitsubmodules again
git submodule update --init --recursive

# finds all files in the current directory that are not executable (not ./install) and symlinks them.
find ~/dotfiles -maxdepth 1 -type f \! -perm -u=x -name '[!.]*' -print0 | xargs -0 -I{} basename {} | xargs -I{} ln -sf ~/dotfiles/{} ~/.{}

# finds all files in the current directory that are not executable (not ./install) and symlinks them.
find ~/dotfiles/config -maxdepth 1 -type f \! -perm -u=x -name '[!.]*' -print0 | xargs -0 -I{} basename {} | xargs -I{} ln -sf ~/dotfiles/config/{} ~/.config/{}

# symlinks vim directory
rm -f ~/.vim # remove any existing symlinks. If this is a directory, the script will fail.
ln -s ~/dotfiles/vim ~/.vim

# symlinks .bash (for git-aware prompt)
rm -f ~/.bash # remove any existing symlinks. If this is a directory, the script will fail.
ln -s ~/dotfiles/bash ~/.bash

# fzf
rm -f ~/.fzf
ln -s ~/dotfiles/fzf ~/.fzf
~/.fzf/install --no-update-rc --completion --key-bindings

rm -f ~/.pyenv
ln -s ~/dotfiles/pyenv ~/.pyenv
