#!/usr/bin/env bash

# finds all files in the current directory that are no executable (not ./setup) and symlinks them.

find ~/dotfiles/ -maxdepth 1 -type f \! -perm -u=x -print0 | xargs -0 -I{} basename {} | xargs -I{} ln -sf ~/dotfiles/{} ~/.{}
