add_newline = false
format = "$python$conda$hostname$directory$fill$git_status$git_state$git_branch\n$character"

[character]
success_symbol = "[\\$](bold fg:green)"
error_symbol = "[\\$](bold fg:red)"
vicmd_symbol = "[*](fg:yellow)"

[aws]
disabled = true

[directory]
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[fill]
symbol = ' '

[git_branch]
format = "[$branch]($style)"
symbol = ''
style = "bold bright-purple"

[git_state]
style = "bold bright-purple"

[git_status]
style = "bold bright-purple"

[hostname]
format = "[$hostname]($style) "
disabled = false
ssh_only = false

[line_break]
disabled = false

[python]
version_format = "${raw}"
format = '[(\(($virtualenv )${version}\) )]($style)'

[conda]
format = '[\($environment\)]($style) '
style = "bold yellow"
