# This file is for interactive shells

# shell options
setopt NO_CASE_GLOB
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY

# expire duplicates first
setopt HIST_EXPIRE_DUPS_FIRST 
# do not store duplications
setopt HIST_IGNORE_DUPS
#ignore duplicates when searching
setopt HIST_FIND_NO_DUPS
# removes blank lines from history
setopt HIST_REDUCE_BLANKS
# expands !! before executing
setopt HIST_VERIFY

unsetopt correct
unsetopt correct_all
DISABLE_CORRECTION="true"

# common between bash and zsh
[[ -f ~/.shared/rc ]] && source ~/.shared/rc


# Autocomplete
autoload -U compinit; compinit
fpath+=~/.zfunc

# case insensitive path-completion
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# partial completion suggestions
zstyle ':completion:*' list-suffixeszstyle ':completion:*' expand prefix suffix

# vim bindings 
bindkey -v

# third-party tools

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zoxide
if command -v zoxide 1>/dev/null 2>&1; then
  eval "$(zoxide init --cmd cd zsh)"
fi

# If cd takes forever, then consider setting this command once, rather than upon every invocation.
cd() {
    if [[ $(whence -w __zoxide_z) == "__zoxide_z: function" ]]; then
        __zoxide_z "$@"
    else
        builtin cd "$@"
    fi
}

# prompts
eval "$(starship init zsh)"


# adds folder-specifc history for the `jog` command 
function zshaddhistory() {
	echo "${1%%$'\n'}|${PWD} &&&" >> ~/.jog_history
}

function jog() {
  grep -a --color=never "${PWD} &&&" ~/.jog_history | grep -v --color=never "jog|${PWD} &&&" | tail | awk -F "|" '{ print 10-NR " " $1 }'
}
